### ISSUE TITLE
Handling row... Error: std::exception

### ISSUE THREAD

**Issue by paulagranados** [amoe/figshare-uploader#1]
Hello, I am trying to use the uploader with my own data and with the example files but I always get the same error: 
Handling row...
Error: std::exception

I have saved the example files from the git and followed all the instructions but the error persists. Could you provide some guidance?
Many thanks, 
Paula

**Comment by amoe** [comment]
Hello Paula, thanks for your interest.  Could you let me know which operating system you are using?  I'll need to see a copy of the log file that `figshare-uploader` produces.

* MacOS: `~/Library/Caches/main/figshare-uploader.log`
* Windows: `C:/Users/<USER>/AppData/Local/main/cache/figshare-uploader.log`

Those locations might not quite be accurate -- I'd be interested to know if they are right or wrong.  Searching your system for `figshare-uploader.log` should find the log file.  I could also do with exact copies of the XLSX and JSON files that are being used, if you would be able to upload them somewhere, or perhaps attach them to this ticket.

**Comment by amoe** [comment]
Hi @paulagranados, I'm thinking about closing this issue, unless you have more info to add?
