### ISSUE TITLE
Unsupported / not working 'Item Types'

### ISSUE THREAD

**Issue by D-Strange** [amoe/figshare-uploader#2]
From a limited bit of testing I found that it is only possible to choose one of the first 4 'Item Types' (1,2,3 & 5) when using the uploader based on mapping logic below.

I've specifically been trying to upload items using the uploader which I'd classify under Online resource, but I receive the following error code - "Error: unknown value in defined type converter"

Current workaround would be to use the upload using a working 'item type' and then batch-edit records on the Figshare interface to adjust to desired item type, which is a very quick and easy solution.

Any fix that could be implemented for this would be great!

Cheers, Damon.

1 - Figure, 2 - Media, 3 - Dataset, 5 - Poster, 6 - Journal contribution, 7 - Presentation, 8 - Thesis, 9 - Software, 11 - Online resource, 12 - Preprint, 13 - Book, 14 - Conference contribution, 15 - Chapter, 16 - Peer review, 17 - Educational resource, 18 - Report, 19 - Standard, 20 - Composition, 21 - Funding, 22 - Physical object, 23 - Data management plan, 24 - Workflow, 25 - Monograph, 26 - Performance, 27 - Event, 28 - Service, 29 - Model

[Item list was found here](https://docs.figshare.com/#articles_list)

**Comment by amoe** [comment]
Hi @D-Strange, I wasn't aware that Github automatically closes the issue when you reference it in a PR.

I've just pushed new Mac and Windows builds for 2.3 that *should* have this support.  Let me know if it works for you.

I'm a bit wary that the platform I use to make the Mac builds might be rather long in the tooth now, so do let me know if you have any issues with it.

**Comment by D-Strange** [comment]
Hi @amoe

Just gave the new build a whirl on Mac, and I can confirm I was able to successfully upload / create an item via the Uploader using 'Online resource' as the item type.

Many thanks for implementing this update so swiftly - will be very helpful.
