### ISSUE TITLE
Uploading Records with Multiple Categories?

### ISSUE THREAD

**Issue by D-Strange** [amoe/figshare-uploader#5]
Hi @amoe,

Have you ever tested / used the uploader to move records that want to be created within 2 or more different categories on Figshare?

I tried doing this, and I get a "Error: category title not found", I'm 100% confident the categories do exist and I'm using a ", " (comma with a space) as the delimiter as I believe I should be for this field.

Is this user error, or is there a bug for this field?

Cheers, Damon.

**Comment by amoe** [comment]
Hi Damon,
It looks like we don't currently support specifying multiple values when using `LookupList`-type encoders, as the category one is.  The delimiter is just ignored at the moment.
I'll try to make some time to look at this.
Cheers.
Dave

**Comment by D-Strange** [comment]
Hi @amoe 

Nice one, current work around I've found is once used your figshare-uploader to get the items / data on there in 1 category, I then use the Figshare supported batch migration tool to update / add the additional categories.....bit fiddly, but better than manually updating 100s of records :) 

Cheers, Damon.

**Comment by amoe** [comment]
Hi @D-Strange, I've released 2.4 which should add support for this.  The default delimiter is a comma with optional whitespace afterwards.  Let me know if it helps for you.

**Comment by D-Strange** [comment]
Hi @amoe, Excellent - many thanks for performing the update, just tested it and it works as expected, which is really helpful. Bw, Damon.
