### ISSUE TITLE
Category Field No Longer Works (Post-Figshare FoR Code updates)

### ISSUE THREAD

**Issue by D-Strange** [amoe/figshare-uploader#7]
Hi,

Over the past couple of months the Figshare-Uploader no longer allows you to define categories for records that are being uploaded / created via the tool.

I know Figshare have recently made the 'Category' field a non-mandatory field and have recently gone through the process of updating category fields as part of recent Fields of Research (FoR) code updates. I assume these changes have probably had an impact.

Not necessarily the end of the world, as we can retrospectively add Categories on the Figshare side, however, thought I'd raise it with you as it would be nice to see it working again.

Thanks, Damon.

![image](https://user-images.githubusercontent.com/92850134/235883829-aacb6998-dab7-4af4-b8d3-370d0848de8b.png)

**Comment by amoe** [comment]
Thanks for reporting this Damon, I only just noticed this issue.  I'll try to carve out some time to take a look at it.

**Comment by amoe** [comment]
Hi @D-Strange 

It seems that what's happened is that Figshare has removed support for a lot of the older categories that existed, and added a lot of new ones.

I wasn't able to use the `Computer Software` category any more.

I've posted up a list of current usable categories here:
https://gist.github.com/amoe/9784ec9cca4b46f03ebb82f388d95b1b

The internal numeric figshare ID is listed here first (but you shouldn't include this in the XLSX file).
I think that if you update the categories in your XLSX file to ones that are listed here, the uploader should work again.

**Comment by D-Strange** [comment]
Hi @amoe,

Nice one, thanks for looking into this. I've just tested it and categories work perfectly again.
